# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: asperation-ai-internship
version: '0.0.0'
github: "JamesMcGuigan/asperation-ai-internship"
license: MIT
author: "James McGuigan"
maintainer: "James McGuigan"
# synopsis: A new Haskeleton package.
# description: asperation-ai-internship is a new Haskeleton package.
# category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options: -Wall

library:
  dependencies:
  - base
  source-dirs: library

executables:
  asperation-ai-internship:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - asperation-ai-internship
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

benchmarks:
  asperation-ai-internship-benchmarks:
    source-dirs: benchmark
    main: Main.hs
    dependencies:
    - base
    - asperation-ai-internship
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  asperation-ai-internship-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - asperation-ai-internship
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
